const APPLICATION_CONSTANTS = {
  // FRAMEWORK
  FRAMEWORK: 'vue',

  MOBILE_LAYOUT_WIDTH: 380,
  SPLITSCREEN_MINIMUM_WIDTH: 500,
  VIEWNOTE_PADDING: 69,
  VIEWNOTE_PADDING_MOBILE: 52,
  DEFAULT_PAGE: '/notebooks',
  LOGIN_PAGE: `/login`,
  REFRESH_TOKEN_INTERVAL: 5 * 60 * 1000,

  // ERROR MESSAGES
  SIGNUP_INVALID_USERNAME: `At least 3 characters required`,
  SIGNUP_INVALID_PASSWORD: `At least 7 characters required`,
  SIGNUP_INVALID_EMAIL: `Please enter a valid email address.`,
  SIGNUP_EMAIL_REGISTERED: `An account with this email already exists.`,
  SIGNUP_GENERAL: `We couldn't create your account. Please try again.`,
  EMAIL_INVALID: `Enter a valid email address`,
  /* Error message map (toUserFriendlyError) */
  ERROR_FALLBACK: `Unknown error`,
  ERROR_UNKNOWN: `Unknown error`,
  ERROR_NETWORK: `Please check your network and try again.`,
  ERROR_NOT_FOUND: `The requested resource was not found.`,
  ERROR_SERVER: `Something went wrong. Please try again later.`,
  ERROR_TIMEOUT: `The request took too long. Please try again.`,
  ERROR_CORS: `A connection error occurred. Please try again.`,
  ERROR_SERVER_UNREACHABLE: `The server could not be reached. Please try again.`,
  REFRESH_TOKEN_ERROR: `Failed to retrieve a valid refresh token.`,
  GENERAL_ERROR: 'Something went wrong — please try again',
  CREATE_NOTEBOOK_ERROR: `We couldn't create the notebook. Please try again.`,
  CREATE_NOTE_ERROR: `We couldn't create the note. Please try again.`,
  CREATE_USER_ERROR: `We couldn't create your account.`,
  CHANGE_USER_GENERAL: `We couldn't update your username. Please try again.`,
  CHANGE_USER_ERROR: `We couldn't update your username. Please try again.`,
  CHANGE_USER_UNIQUE: `Please enter a different username.`,
  CHANGE_USER_TOO_FEW: `Username must be at least 3 characters.`,
  CHANGE_USER_TOO_MANY: `Username must be less than 10 characters.`,
  CHANGE_PASS_UNIQUE: `The new password must be different from your current password.`,
  CHANGE_PASS_TOO_FEW: `Password must be at least 7 characters.`,
  CHANGE_PASS_TOO_MANY: `Password must be less than 10 characters.`,
  CHANGE_PASS_LENGTH: `The two new passwords do not match.`,
  CHANGE_PASS_ERROR: `We couldn't change your password. Please try again.`,
  LOGOUT_ERROR: `There was a problem logging out.`,
  LOGIN_ERROR: `Invalid email and password combination.`,
  UNAUTHORIZED: `Your session has expired — please sign in again`,
  USERNAME_MIN: 3,
  USERNAME_MAX: 10,
  PASSWORD_MIN: 7,
  PASSWORD_MAX: 10,
  NOTEBOOK_NAME_MIN: 3,
  NOTEBOOK_NAME_MAX: 10,
  NOTEBOOK_NAME_MIN_ERROR: `The notebook name must be at least 3 characters.`,
  NOTEBOOK_NAME_MAX_ERROR: `The notebook name must be less than 10 characters.`,
  NOTEBOOK_COVER_EMPTY: `Please select a cover.`,
  NOTEBOOKS_ERROR: `We couldn't load your notebooks. Please try again.`,
  NOTEBOOK_ERROR: `We couldn't load the notebook. Please try again.`,
  NOTEBOOK_CREATE_ERROR: `We couldn't create the notebook. Please try again.`,
  NOTEBOOK_DELETE_ERROR: `We couldn't delete the notebook. Please try again.`,
  NOTE_ERROR: `We couldn't load the note. Please try again.`,
  NOTES_ERROR: `We couldn't load the notes. Please try again.`,
  NOTE_CREATE_ERROR: `We couldn't create the note. Please try again.`,
  NOTES_DELETE_ERROR: `We couldn't delete the notes. Please try again.`,
  NOTE_SAVE_ERROR: `We couldn't save the note. Please try again.`,
  NOTEBOOK_UPDATE_DATE_ERROR: `We couldn't update the notebook date. Please try again.`
}

export default APPLICATION_CONSTANTS
